# remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
# | horizontal 
# - vertical
bind '\' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

# allow mouse in TMUX
set -g mouse on

# vi-copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind-key y run-shell "tmux show-buffer | xclip -selection clipboard"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# increase scrollback history
set -g history-limit 20000

# alt+ijkl to move around
bind -n M-i select-pane -U
bind -n M-j select-pane -L
bind -n M-k select-pane -D
bind -n M-l select-pane -R

set-option -g allow-rename off

# c-n/p to move windows
bind-key -n C-p previous-window
bind-key -n C-n next-window

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-ukiyo'

# theme
set -g @ukiyo-theme "tokyonight/night"
set -g @ukiyo-show-powerline true
set -g @ukiyo-plugins "cpu-usage gpu-usage ram-usage"


# init tpm
run '~/.config/tmux/plugins/tpm/tpm'
